parameters:

  available_currencies:
    EURO: EUR
    UNITED_STATES_DOLLAR: USD
    JAPANESE_YEN: JPY

  conversion_courses:
    EUR_TO_USD: 1.1497
    EUR_TO_JPY: 129.53

  pricing:
    MONEY_DEPOSIT_PERCENT: 0.03
    MONEY_DEPOSIT_MAXIMUM_COMMISSION: 5.00
    CASH_CLEARING_PERCENT: 0.3
    CASH_CLEARING_MINIMUM_COMMISSION: 0.50
    CASH_CLEARING_AMOUNT_OF_TIMES_FREE_FOR_NATURAL_PEOPLE: 3
    CASH_CLEARING_FREE_AMOUNT: 1000